#!/usr/bin/env python

import sys, traceback
import numpy as np

def main():

    dt = sys.argv[1]
    if(len(sys.argv) == 6):
        try:
            M = int(sys.argv[2])
        except:
            sys.exit(1)
        N = M
        L = M
        file1 = sys.argv[3]
        file2 = sys.argv[4]
        file3 = sys.argv[5]
    elif(len(sys.argv) == 8):
        try:
            M = int(sys.argv[2])
            N = int(sys.argv[3])
            L = int(sys.argv[4])
        except:
            sys.exit(1)
        file1 = sys.argv[5]
        file2 = sys.argv[6]
        file3 = sys.argv[7]
    else:
        sys.exit(1)

    if(N<1 or M<1 or L<1):
        sys.exit(1)
    if(dt != "double" and dt != "int"):
        sys.exit(1)
    try:
        m1 = np.loadtxt(file1)
        m2 = np.loadtxt(file2)
    except:
        sys.exit(2)

    if dt == "int" :

        if '.' in open(file1).read():
                sys.exit(3)
        if '.' in open(file2).read():
                sys.exit(3)
    
    if(m1.size != M*N or m2.size != N*L):
        sys.exit(3)
    m1 = np.reshape(m1, (M, -1))
    m2 = np.reshape(m2, (N, -1))
    
    m3 = np.mat(m1)*np.mat(m2)
    try:
        if(dt=="int"):
            np.savetxt(file3, m3, delimiter=" ", fmt='%d')
        else:
            np.savetxt(file3, m3, delimiter=" ", fmt='%f')
    except:
        sys.exit(4)

if __name__ == "__main__":
        main()
